# SPDX-License-Identifier: MIT
# Copyright (c) 2025-present K. S. Ernest (iFire) Lee
#
# Minimal glTF JSON load/save. Preserves extensions and extras.

(import aria/gltf/state :as S)
(import aria/json_minimal :as JSON)

(defn load-json [json-str]
  (def data (JSON/decode json-str))
  (def state (S/state-new))
  (put state :json (if data data @{}))
  (when data
  (when (get data "nodes")
    (put state :nodes (get data "nodes")))
  (when (get data "buffers")
    (put state :buffers (get data "buffers")))
  (when (get data "bufferViews")
    (put state :buffer_views (get data "bufferViews")))
  (when (get data "accessors")
    (put state :accessors (get data "accessors")))
  (when (get data "meshes")
    (put state :meshes (get data "meshes")))
  (when (get data "materials")
    (put state :materials (get data "materials")))
  (when (get data "textures")
    (put state :textures (get data "textures")))
  (when (get data "images")
    (put state :images (get data "images")))
  (when (get data "animations")
    (put state :animations (get data "animations")))
  (when (get data "skins")
    (put state :skins (get data "skins")))
  (when (get data "cameras")
    (put state :cameras (get data "cameras")))
  (when (get data "extensionsUsed")
    (put state :extensions_used (get data "extensionsUsed")))
  (when (get data "extensionsRequired")
    (put state :extensions_required (get data "extensionsRequired")))
  (when (get data "scene")
    (put state :root_nodes (get data "scene"))))
  state)

(defn save-json [state]
  (def data (table/clone (get state :json @{})))
  (when (get state :nodes) (put data "nodes" (get state :nodes)))
  (when (get state :buffers) (put data "buffers" (get state :buffers)))
  (when (get state :buffer_views) (put data "bufferViews" (get state :buffer_views)))
  (when (get state :accessors) (put data "accessors" (get state :accessors)))
  (when (get state :meshes) (put data "meshes" (get state :meshes)))
  (when (get state :materials) (put data "materials" (get state :materials)))
  (when (get state :textures) (put data "textures" (get state :textures)))
  (when (get state :images) (put data "images" (get state :images)))
  (when (get state :animations) (put data "animations" (get state :animations)))
  (when (get state :skins) (put data "skins" (get state :skins)))
  (when (get state :cameras) (put data "cameras" (get state :cameras)))
  (when (get state :extensions_used) (put data "extensionsUsed" (get state :extensions_used)))
  (when (get state :extensions_required) (put data "extensionsRequired" (get state :extensions_required)))
  (when (get state :root_nodes) (put data "scene" (get state :root_nodes)))
  (JSON/encode data))
